version: '3'
services:
  tito-api:    
    image: dynamikarray/tito:latest
    restart: always
    build: .
    ports:
      - "8000:8000"
    networks:
      - tito-net    
    links:
      - mongo      
    depends_on:
      - mongo                

  ## MONDO DB ##
  mongo:
    container_name: mongo-tito
    restart: always
    image: mongo    
    volumes:
      - "./dbdata:/data/db"
    ports:
      - "27017:27017"
    networks:
      - tito-net

volumes:
  dbdata:
    driver: local

networks:
  tito-net:
    driver: bridge
