export const SEARCH_TOWELS_RESULTS = "SEARCH_TOWELS_RESULTS";
export const SEARCH_TOWELS_RESULTS_LOADING = "SEARCH_TOWELS_RESULTS_LOADING";
export const REMOVE_TOWEL_FROM_RESULTS = "REMOVE_TOWEL_FROM_RESULTS";
