module.exports = [
  {
    brand: "JCPenney",
    color: "Paisley Purple",
    quantity: "2.5",
    upc: "",
    Hood: "Everest, Sophia, Rapunzel",
    Body: "Everest, Sophia, Rapunzel",
  },
  {
    brand: "JCPenney",
    color: "Mum (Yellow)",
    quantity: "23.5",
    upc: "",
    Hood: "Batman, Marshall, Iron Man, Belle, Tigger, Elephant, Elmo",
    Body: "Minions, Rubble, Snow White, Pokemon, Pooh, Silly Face",
  },
  {
    brand: "JCPenney",
    color: "Carnvial Pink",
    quantity: "1.5",
    upc: "",
    Hood: "Minion",
    Body: "Unicorn, Caticorn",
  },
  {
    brand: "JCPenney",
    color: "Tangerine Tango",
    quantity: 1,
    upc: "",
    Hood: "TMNT",
    Body: "Tigger,  Zuma",
  },
  {
    brand: "JCPenney",
    color: "Dark Citron",
    quantity: "1.5",
    upc: "",
    Hood: "Tinkerbell",
    Body: "Tinkerbell, Dino, T-Rex, Frog",
  },
  {
    brand: "JCPenney",
    color: "Aruba Blue",
    quantity: 2,
    upc: "",
    Hood: "Elsa, Skye",
    Body: "Elsa, Llama",
  },
  {
    brand: "JCPenney",
    color: "Always Violet",
    quantity: 10,
    upc: "",
    Hood: "TMNT",
    Body: "Unicorn",
  },
  {
    brand: "JCPenney",
    color: "HP Simply Purple",
    quantity: 46,
    upc: 7404141199501,
    Hood: "Everest, Sophia, Rapunzel",
    Body: "Everest, Sophia, Rapunzel",
  },
  {
    brand: "JCPenney",
    color: "HP Canadian Red",
    quantity: "82.5",
    upc: 740414190801,
    Hood: "",
    Body: "Marshall, Iron Man, Spiderman, Angry Bird, Elmo",
  },
  {
    brand: "JCPenney",
    color: "HP Blue Aster",
    quantity: "46.5",
    upc: "",
    Hood: "Cinderella, Snow White, Giraffe, Frog, Dino, TMNT, Puppy Dog Pal",
    Body: "Cookie Monster, Thomas, Cinderella",
  },
  {
    brand: "JCPenney",
    color: "HP Black",
    quantity: 82,
    upc: 7404141040301,
    Hood: "Angry Bird",
    Body: "Batman, Darth Vader, Panda, Penquins",
  },
  {
    brand: "JCPenney",
    color: "HP Scuba Blue",
    quantity: "103.5",
    upc: 7404141020501,
    Hood: "Elsa, Jasmine, Duck, Elephant, Unicorn",
    Body: "Elas, Jasmine, Anna",
  },
  {
    brand: "JCPenney",
    color: "HP Bright White",
    quantity: 26,
    upc: 7404141010601,
    Hood: "Alice, Silly Face",
    Body: "Storm Trooper Buzz, Forky",
  },
  {
    brand: "JCPenney",
    color: "HP Raffia Beige",
    quantity: 3,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "JCPenney",
    color: "HP Stunning Sapphire",
    quantity: 48,
    upc: "",
    Hood: "",
    Body: "Chase",
  },
  {
    brand: "JCPenney",
    color: "HP Gun Metal",
    quantity: 40,
    upc: "",
    Hood: "Chase, Rubble, Storm Trooper, Shark",
    Body: "Elephants",
  },
  {
    brand: "JCPenney",
    color: "HP Happy Green",
    quantity: 55,
    upc: 7404141110401,
    Hood: "",
    Body: "",
  },
  {
    brand: "JCPenney",
    color: "HP Whimiscal Yellow",
    quantity: "25.5",
    upc: 7404141080901,
    Hood: "",
    Body: "Duck, Baby Shark",
  },
  {
    brand: "JCPenney",
    color: "HP Madrid Rose",
    quantity: 25,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "JCPenney",
    color: "HP Pink Flower",
    quantity: 25,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "JCPenney",
    color: "Enamel Blue",
    quantity: 6,
    upc: 7404141130201,
    Hood: "",
    Body: "",
  },

  {
    brand: "Target",
    color: "Ebony (Black)",
    quantity: ".5",
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Target",
    color: "Teal",
    quantity: "15.5",
    upc: "",
    Hood: "Mermaid Tail, Skye, Light Fury, Moana, Pig",
    Body: "",
  },
  {
    brand: "Target",
    color: "Yellow",
    quantity: "12 1/4",
    upc: "",
    Hood: "Elephant",
    Body: "Duck, Baby Shark",
  },
  {
    brand: "Target",
    color: "OH Placid Blue",
    quantity: 7,
    upc: "",
    Hood: "Olfa",
    Body: "Olfa",
  },
  {
    brand: "Target",
    color: "OH Capri Blue",
    quantity: "20.5",
    upc: "",
    Hood: "",
    Body: "Wonder Woman, Captain America, Woody, Jessie",
  },
  {
    brand: "Target",
    color: "OH Sandal Wood",
    quantity: 1,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Target",
    color: "OH Jet Gray",
    quantity: 6,
    upc: 490641113205,
    Hood: "",
    Body: "",
  },
  {
    brand: "Target",
    color: "Hot Pink",
    quantity: 0,
    upc: "",
    Hood: "",
    Body: "Unicorn",
  },
  {
    brand: "Target",
    color: "OH Bluff Green",
    quantity: 29,
    upc: "",
    Hood: "",
    Body: "Ariel, Hulk",
  },
  {
    brand: "Target",
    color: "Bright Blue",
    quantity: "3/4",
    upc: "",
    Hood: "Sorting Hat",
    Body: "",
  },
  {
    brand: "Target",
    color: "Capri Blue (BS)",
    quantity: 3,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Target",
    color: "Jet Gray (BS)",
    quantity: 1,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Target",
    color: "Ebony (Black) (BS)",
    quantity: 1,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Target",
    color: "Dancing Blue",
    quantity: 1,
    upc: "",
    Hood: "",
    Body: "",
  },

  {
    brand: "Kohl's",
    color: "Big One  - Sandstone",
    quantity: 20,
    upc: "",
    Hood: "Teddy Bear, Crush, Cookie Monster, PJ Masks, Fox",
    Body: "Teddy Bear",
  },
  {
    brand: "Kohl's",
    color: "Big One - Slate Brown",
    quantity: 12,
    upc: "",
    Hood: "T-Rex",
    Body: "Teddy Bear, Poop, Ewok",
  },
  {
    brand: "Kohl's",
    color: "Pink",
    quantity: "89.5",
    upc: 400948572735,
    Hood: "Minnie, Hello Kitty, Llama, Teddy Bear, Cat, Big Eyed Girl, Zebra",
    Body: "Minnie, Pinkie Pie, Hello Kitty, Abby, Mermaid",
  },
  {
    brand: "Kohl's",
    color: "Pearl",
    quantity: 4,
    upc: "",
    Hood: "Teddy Bear, Poop",
    Body: "",
  },
  {
    brand: "Kohl's",
    color: "Raspberry",
    quantity: ".5",
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Kohl's",
    color: "Dark Blue",
    quantity: 48,
    upc: "",
    Hood: "Spiderman",
    Body: "Chase",
  },
  {
    brand: "Kohl's",
    color: "Medium Gray",
    quantity: 46,
    upc: "",
    Hood: "Chase, Rubble, Storm Trooper, Shark, Darth Vader",
    Body: "Rocky, Zebra",
  },
  {
    brand: "Kohl's",
    color: "Spearmint",
    quantity: "61.5",
    upc: 400949170343,
    Hood: "Rocky, Panda",
    Body: "TMNT, PJ Masks, Cat, Ariel",
  },
  {
    brand: "Kohl's",
    color: "Purple (Dark)",
    quantity: 0,
    upc: "",
    Hood: "Rapunzel, Everest, Sofia, Shimmer",
    Body: "Rapunzel, Everest, Sofia, Shimmer",
  },
  {
    brand: "Kohl's",
    color: "Dark Pink",
    quantity: "16.5",
    upc: "",
    Hood: "Elephant",
    Body: "Skye, Peppa",
  },
  {
    brand: "Kohl's",
    color: "Coral",
    quantity: "20.5",
    upc: "",
    Hood: "Pony",
    Body: "Moana",
  },
  {
    brand: "Kohl's",
    color: "Bright Orange",
    quantity: "4.5",
    upc: "",
    Hood: "BB8",
    Body: "BB8",
  },
  {
    brand: "Kohl's",
    color: "Purple",
    quantity: "35.5",
    upc: "",
    Hood: "Minnie, Giraffe, Sophia, Everest, Teddy Bear",
    Body: "Minnie, Sophia, Everest",
  },
  {
    brand: "Kohl's",
    color: "Tango Red",
    quantity: 81,
    upc: "",
    Hood:
      "Woody, Puppy Dog Pal, Capt. America, Wonder Woman, Mickey, Minnie, Pokemon, TMNT, Pooh, Lego Boy, Daniel Tiger",
    Body:
      "Marshall, Minnie, MIckey, Iron Man, Spiderman, PJ Mask, Lightning, Elmo, Angry Bird",
  },
  {
    brand: "Kohl's",
    color: "Black",
    quantity: 58,
    upc: 400949170329,
    Hood: "",
    Body: "Mickey, Penquin, Panda, Toothless, Cat in Hat, Darth Vader, Batman",
  },
  {
    brand: "Kohl's",
    color: "Light Gray",
    quantity: "28.5",
    upc: "",
    Hood:
      "Toothless, Cookie Monster, Darth Vader, Storm Trooper, Rubble, Chase, Peppa, Lego Girl, Silly Face",
    Body: "R2D2",
  },
  {
    brand: "Kohl's",
    color: "Marine",
    quantity: 2,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Kohl's",
    color: "Magenta",
    quantity: 3,
    upc: "",
    Hood: "Anna, Caticorn",
    Body: "Caticorn, Unicorn, Mermaid Tail",
  },
  {
    brand: "Kohl's",
    color: "Turquoise",
    quantity: 19,
    upc: "",
    Hood: "Baby Shark, Boy Giraffe",
    Body: "",
  },
  {
    brand: "Kohl's",
    color: "Light Teal",
    quantity: 7,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Kohl's",
    color: "Blue",
    quantity: 1,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Kohl's",
    color: "Dove (White)",
    quantity: 1,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Kohl's",
    color: "Berry",
    quantity: 26,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Kohl's",
    color: "Aqua",
    quantity: "87.5",
    upc: 400551119709,
    Hood: "Duck, Elephant, Unicorn, Dump Truck",
    Body: "",
  },
  {
    brand: "Kohl's",
    color: "Tropic Aqua",
    quantity: 21,
    upc: 400188974610,
    Hood: "",
    Body: "",
  },

  {
    brand: "Bed, B & B",
    color: "Silver",
    quantity: 2,
    upc: "",
    Hood: "",
    Body: "",
  },

  {
    brand: "Walmart",
    color: "Wine",
    quantity: "3.5",
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Walmart",
    color: "Fuschia Blast (pink)",
    quantity: 18,
    upc: "",
    Hood: "",
    Body: "",
  },
  {
    brand: "Walmart",
    color: "Sunray Yellow",
    quantity: "18.5",
    upc: "",
    Hood: "",
    Body: "",
  },
];
